2016-11-03 22:28:07,670 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 4
2016-11-03 22:28:10,210 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 22:28:10,210 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f1e2c53eea0> not found, so no spy added
2016-11-03 22:28:10,236 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 22:28:10,236 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 22:28:10,236 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 22:28:10,236 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 22:28:10,247 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 22:28:10,248 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 22:28:10,248 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 22:28:10,248 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 22:28:10,251 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 22:28:10,259 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 22:28:10,259 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 22:28:10,260 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 22:28:10,261 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 22:28:10,261 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 22:28:10,274 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 22:28:10,277 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 22:28:10,277 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 22:28:10,277 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 22:28:10,277 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 22:28:10,278 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 22:28:10,279 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 22:28:10,280 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 22:28:10,280 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 22:28:10,282 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 22:28:10,282 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 22:28:10,282 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 22:28:10,286 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 22:28:10,286 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 22:28:10,906 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478192290.csv
2016-11-03 22:28:10,907 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Client9 is b'0000000000000000000000000Client9', its len is 32
2016-11-03 22:28:10,908 | DEBUG    | client.py            (76) | __init__ | Client Client9 ignoring given ha HA(host='0.0.0.0', port=6641) and using HA(host='127.0.0.1', port=6074)
2016-11-03 22:28:10,908 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 22:28:10,908 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 22:28:11,014 | INFO     | client.py            (121) | __init__ | Client Client9 initialized with the following node registry:
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node1C listens at 35.161.137.38  on port 9702
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node2C listens at 35.161.111.17  on port 9704
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node3C listens at 35.161.122.249 on port 9706
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node4C listens at 35.160.153.163 on port 9708
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node5C listens at 54.147.219.106 on port 9710
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node6C listens at 52.199.48.127  on port 9712
2016-11-03 22:28:11,015 | INFO     | client.py            (128) | __init__ |     Node7C listens at 54.169.186.146 on port 9714
2016-11-03 22:28:11,015 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 22:28:11,784 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 22:28:11,784 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 22:28:11,784 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 22:28:11,785 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 22:28:11,785 | DEBUG    | motor.py             (34) | set_status | Client9 changing status from stopped to starting
2016-11-03 22:28:11,785 | INFO     | stacked.py           (75) | start | stack Client9 starting at ('0.0.0.0', 6074) in always mode
2016-11-03 22:28:11,785 | INFO     | stacked.py           (851) | start | Client9 listening for other nodes at 0.0.0.0:6074
2016-11-03 22:28:11,785 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node4C
2016-11-03 22:28:11,790 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,790 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node3C
2016-11-03 22:28:11,795 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,795 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node7C
2016-11-03 22:28:11,801 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,801 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node6C
2016-11-03 22:28:11,807 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,807 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node5C
2016-11-03 22:28:11,812 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,813 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node2C
2016-11-03 22:28:11,818 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,818 | DEBUG    | stacked.py           (573) | handleDisconnectedRemote | Client9 retrying to connect with Node1C
2016-11-03 22:28:11,822 | DEBUG    | stacked.py           (585) | handleDisconnectedRemote | Client9 disconnected node is joined
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Client9 nodereg is odict_items([('Node1C', HA(host='35.161.137.38', port=9702)), ('Node2C', HA(host='35.161.111.17', port=9704)), ('Node3C', HA(host='35.161.122.249', port=9706)), ('Node4C', HA(host='35.160.153.163', port=9708)), ('Node5C', HA(host='54.147.219.106', port=9710)), ('Node6C', HA(host='52.199.48.127', port=9712)), ('Node7C', HA(host='54.169.186.146', port=9714))])
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Client9 nodestack is ['Node4C', 'Node3C', 'Node7C', 'Node6C', 'Node5C', 'Node2C', 'Node1C']
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 2 ('35.160.153.163', 9708)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 6 ('35.161.122.249', 9706)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 7 ('54.169.186.146', 9714)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 5 ('52.199.48.127', 9712)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 3 ('54.147.219.106', 9710)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 8 ('35.161.111.17', 9704)
2016-11-03 22:28:11,823 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 4 ('35.161.137.38', 9702)
2016-11-03 22:28:11,824 | DEBUG    | stacked.py           (490) | maintainConnections | Client9 next check for retries in 6.00 seconds
2016-11-03 22:28:11,826 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:12,203 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:12,580 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:12,956 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:13,332 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:13,709 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:14,087 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:14,464 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:14,840 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:15,218 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:15,594 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:15,970 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:16,347 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:16,724 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:17,100 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:17,477 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:17,787 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,787 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,787 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,787 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,788 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,788 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,788 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Client9 allow already in process, so waiting to check for reconnects
2016-11-03 22:28:17,788 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Client9 nodereg is odict_items([('Node1C', HA(host='35.161.137.38', port=9702)), ('Node2C', HA(host='35.161.111.17', port=9704)), ('Node3C', HA(host='35.161.122.249', port=9706)), ('Node4C', HA(host='35.160.153.163', port=9708)), ('Node5C', HA(host='54.147.219.106', port=9710)), ('Node6C', HA(host='52.199.48.127', port=9712)), ('Node7C', HA(host='54.169.186.146', port=9714))])
2016-11-03 22:28:17,788 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Client9 nodestack is ['Node4C', 'Node3C', 'Node7C', 'Node6C', 'Node5C', 'Node2C', 'Node1C']
2016-11-03 22:28:17,788 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 2 ('35.160.153.163', 9708)
2016-11-03 22:28:17,788 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 6 ('35.161.122.249', 9706)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 7 ('54.169.186.146', 9714)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 5 ('52.199.48.127', 9712)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 3 ('54.147.219.106', 9710)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 8 ('35.161.111.17', 9704)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Client9 matched remote is 4 ('35.161.137.38', 9702)
2016-11-03 22:28:17,789 | DEBUG    | stacked.py           (490) | maintainConnections | Client9 next check for retries in 6.00 seconds
2016-11-03 22:28:17,853 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:18,230 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:18,607 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:18,983 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:19,359 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:19,736 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:20,112 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:20,490 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:20,866 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:21,243 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:21,619 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:21,996 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:22,372 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:22,749 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:23,125 | WARNING  | eventually.py        (133) | eventually | partial(checkIfConnectedToAll) last try...
2016-11-03 22:28:23,125 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 22:28:23,125 | ERROR    | eventually.py        (156) | eventually | partial(checkIfConnectedToAll) failed; not trying any more because 7.499990768999851 seconds have passed; args were ()
2016-11-03 22:28:23,125 | DEBUG    | eventually.py        (79) | eventuallyAll | a coro partial(checkIfConnectedToAll) timed out without succeeding; fail count: 1, acceptable: 0
2016-11-03 22:28:23,125 | ERROR    | looper.py            (230) | wrapper | Error while running coroutine eventuallyAll: Exception('Not connected to any',)
2016-11-03 22:28:23,126 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 22:28:23,127 | DEBUG    | motor.py             (34) | set_status | Client9 changing status from starting to stopping
2016-11-03 22:28:23,128 | INFO     | stacked.py           (82) | stop | stack Client9 stopped
2016-11-03 22:28:23,128 | DEBUG    | motor.py             (34) | set_status | Client9 changing status from stopping to stopped
2016-11-03 22:28:23,128 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.002 seconds.
Traceback (most recent call last):
  File "gen_load_ratcheting", line 331, in <module>
    main(commandLineArgs)
  File "gen_load_ratcheting", line 314, in main
    retryWait=RETRY_WAIT))
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 240, in run
    return self.loop.run_until_complete(what)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 231, in wrapper
    raise ex
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/common/looper.py", line 219, in wrapper
    results.append(await coro)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 74, in eventuallyAll
    verbose=False)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 157, in eventually
    raise ex
  File "/home/lovesh/dev/evernym/plenum-priv/plenum/test/eventually.py", line 135, in eventually
    res = coroFunc(*args)
  File "gen_load_ratcheting", line 219, in checkIfConnectedToAll
    raise Exception("Not connected to any")
Exception: Not connected to any
2016-11-03 22:28:23,184 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
